services:
  - type: web
    name: tw-stock-screener
    env: python
    plan: free
    rootDir: stock_screener_web
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
