[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
enableWebsocketCompression = true
# Keep websocket compression enabled for Render proxy compatibility

[browser]
gatherUsageStats = false
