[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
enableWebsocketCompression = false
# Disable websocket compression to improve compatibility with Render's proxy upgrades

[browser]
gatherUsageStats = false
