[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
enableWebsocketCompression = true
# Explicitly enable websocket compression for Render proxy compatibility

[browser]
gatherUsageStats = false
